### PR TITLE
Fixes / UX Improvements

### PR DESCRIPTION
**Pull request by faroukm15**
1 - Polynomial Parser Improved (New Algorithm) and Fixed parsing free term and first degree term
2 - Polynomial Renderer Improved
3 - Added Polynomial Division (Fully Working)
4 - Added Polynomial Division Reminder [Modulus](Logic Added - Not
added to GUI)

### CODE REVIEW

**Comment by khaledkee** [comment]
@faroukm15 
In [_MainForm.cs_](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/Polynomial-Calculator/CalculatorUI/MainForm.cs), in [_LogInHistory_](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/Polynomial-Calculator/CalculatorUI/MainForm.cs#L174), you don't have a [_case_](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/Polynomial-Calculator/CalculatorUI/MainForm.cs#L194) for [_OperationTypeEnum.Modulus_](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/Polynomial-Calculator/CalculatorUI/MainForm.cs#L25), which means the __historyTrie_ will not store the _Modulus_ operations. Is that on purpose?! 
There is also, I suppose, unnecessary empty method called [_BtnDiv_Click_](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/Polynomial-Calculator/CalculatorUI/MainForm.cs#L645). It may have been, presumably, created by the designer. Consider removing it!

**Comment by sallam-ahmed** [comment]
@faroukm15 
I'll check the parser new algorithm as it manipulates the input value and might fall for signed numbers ( +,-)

**Comment by faroukm15** [comment]
@Ahmed-YehiaGPEL  about expr = expr.Replace("+X", "1X");, just make it expr = expr.Replace("+X", "+1X"); it will fix the problem.

**Comment by sallam-ahmed** [comment]
**Review**
#14 Input string not valid when inputting no coefficient , must be auto calculated as 1
_Example_
image

Check [MainForm.cs](https://github.com/Ahmed-YehiaGPEL/Polynomial-Calculator/blob/Polynomial-Calculator/CalculatorUI/MainForm.cs#L498)

**Comment by khaledkee** [comment]
I think this should fix it:
```cpp
string[] cofpow = s.Split(new string[] { "x^", "X^" }, StringSplitOptions.RemoveEmptyEntries);
double coff = 1;
double.TryParse(cofpow[0], out coff);
sList.Add(int.Parse(cofpow[1]), new Complex(coff,0));
```

**Comment by faroukm15** [comment]
Added Normally!!

captureadded

**Comment by khaledkee** [comment]
I'm just wondering: why there is no button for modulus?!

**Comment by faroukm15** [comment]
mainForm does not have enough space, so I left it for @Ahmed-YehiaGPEL  to find space and add a button.

**Comment by faroukm15** [comment]
I'm just wondering, mdy2een awi mn my code leh? :"D

**Comment by sallam-ahmed** [comment]
Thinking of Improving Main UX
**Issue #16- Main UX Improvement**
_Will add Modulus in the improvement_

**Pull request merged**
